Add Sayantika's entry
rladies/rladies.github.io pull request #185
Opened 2023-07-21 19:08 UTC by cosimameyer

I added Sayantika's entry (https://github.com/rladies/global-team/issues/4)

2023-07-21 19:12 UTC, drmowinckels requested changes
Looks great! Just suggesting to remove the credit bit if there is not credit to be given :)

2023-07-21 19:12 UTC, drmowinckels commented on data/global_team/current/sayantika_banik.json
> +    "url": "sayantika_banik.png",
```suggestion
    "url": "sayantika_banik.png"
```

2023-07-21 19:12 UTC, drmowinckels commented on data/global_team/current/sayantika_banik.json
> +    "credit": ""
```suggestion
```

2023-07-22 03:25 UTC, cosimameyer commented on data/global_team/current/sayantika_banik.json
> +    "credit": ""
Excellent catch, thanks! :)

2023-07-23 19:49 UTC, drmowinckels approved these changes

2023-07-23 20:00 UTC, merged